capturesBaseUrl=YOUR_BASE_URL
googleWebClientId=YOUR_CLIENT_ID
kakaoApiKey=YOUR_API_KEY
appleAuthEndpoint=YOUR_ENDPOINT
appleRedirectUrl=YOUR_REDIRECT_URL
appleResponseUrl=YOUR_RESPONSE_URL
headerKey=YOUR_KEY
headerValue=YOUR_VALUE