package com.captures2024.soongan.core.designsystem.icon.myiconpack

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType.Companion.NonZero
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap.Companion.Butt
import androidx.compose.ui.graphics.StrokeJoin.Companion.Miter
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.ImageVector.Builder
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.captures2024.soongan.core.designsystem.icon.MyIconPack

public val MyIconPack.IconPlus: ImageVector
    get() {
        if (_iconPlus != null) {
            return _iconPlus!!
        }
        _iconPlus = Builder(name = "IconPlus", defaultWidth = 28.0.dp, defaultHeight = 28.0.dp,
                viewportWidth = 28.0f, viewportHeight = 28.0f).apply {
            group {
                path(fill = SolidColor(Color(0xFF252525)), stroke = null, strokeLineWidth = 0.0f,
                        strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                        pathFillType = NonZero) {
                    moveTo(12.6f, 0.0f)
                    verticalLineTo(-2.0f)
                    horizontalLineTo(10.6f)
                    verticalLineTo(0.0f)
                    horizontalLineTo(12.6f)
                    close()
                    moveTo(15.4f, 0.0f)
                    horizontalLineTo(17.4f)
                    verticalLineTo(-2.0f)
                    horizontalLineTo(15.4f)
                    verticalLineTo(0.0f)
                    close()
                    moveTo(12.6f, 12.6f)
                    verticalLineTo(14.6f)
                    horizontalLineTo(14.6f)
                    verticalLineTo(12.6f)
                    horizontalLineTo(12.6f)
                    close()
                    moveTo(0.0f, 12.6f)
                    verticalLineTo(10.6f)
                    horizontalLineTo(-2.0f)
                    verticalLineTo(12.6f)
                    horizontalLineTo(0.0f)
                    close()
                    moveTo(0.0f, 15.4f)
                    horizontalLineTo(-2.0f)
                    verticalLineTo(17.4f)
                    horizontalLineTo(0.0f)
                    verticalLineTo(15.4f)
                    close()
                    moveTo(12.6f, 15.4f)
                    horizontalLineTo(14.6f)
                    verticalLineTo(13.4f)
                    horizontalLineTo(12.6f)
                    verticalLineTo(15.4f)
                    close()
                    moveTo(12.6f, 28.0f)
                    horizontalLineTo(10.6f)
                    verticalLineTo(30.0f)
                    horizontalLineTo(12.6f)
                    verticalLineTo(28.0f)
                    close()
                    moveTo(15.4f, 28.0f)
                    verticalLineTo(30.0f)
                    horizontalLineTo(17.4f)
                    verticalLineTo(28.0f)
                    horizontalLineTo(15.4f)
                    close()
                    moveTo(15.4f, 15.4f)
                    verticalLineTo(13.4f)
                    horizontalLineTo(13.4f)
                    verticalLineTo(15.4f)
                    horizontalLineTo(15.4f)
                    close()
                    moveTo(28.0f, 15.4f)
                    verticalLineTo(17.4f)
                    horizontalLineTo(30.0f)
                    verticalLineTo(15.4f)
                    horizontalLineTo(28.0f)
                    close()
                    moveTo(28.0f, 12.6f)
                    horizontalLineTo(30.0f)
                    verticalLineTo(10.6f)
                    horizontalLineTo(28.0f)
                    verticalLineTo(12.6f)
                    close()
                    moveTo(15.4f, 12.6f)
                    horizontalLineTo(13.4f)
                    verticalLineTo(14.6f)
                    horizontalLineTo(15.4f)
                    verticalLineTo(12.6f)
                    close()
                    moveTo(12.6f, 2.0f)
                    horizontalLineTo(15.4f)
                    verticalLineTo(-2.0f)
                    horizontalLineTo(12.6f)
                    verticalLineTo(2.0f)
                    close()
                    moveTo(14.6f, 12.6f)
                    verticalLineTo(0.0f)
                    horizontalLineTo(10.6f)
                    verticalLineTo(12.6f)
                    horizontalLineTo(14.6f)
                    close()
                    moveTo(0.0f, 14.6f)
                    horizontalLineTo(12.6f)
                    verticalLineTo(10.6f)
                    horizontalLineTo(0.0f)
                    verticalLineTo(14.6f)
                    close()
                    moveTo(2.0f, 15.4f)
                    verticalLineTo(12.6f)
                    horizontalLineTo(-2.0f)
                    verticalLineTo(15.4f)
                    horizontalLineTo(2.0f)
                    close()
                    moveTo(12.6f, 13.4f)
                    horizontalLineTo(0.0f)
                    verticalLineTo(17.4f)
                    horizontalLineTo(12.6f)
                    verticalLineTo(13.4f)
                    close()
                    moveTo(14.6f, 28.0f)
                    verticalLineTo(15.4f)
                    horizontalLineTo(10.6f)
                    verticalLineTo(28.0f)
                    horizontalLineTo(14.6f)
                    close()
                    moveTo(15.4f, 26.0f)
                    horizontalLineTo(12.6f)
                    verticalLineTo(30.0f)
                    horizontalLineTo(15.4f)
                    verticalLineTo(26.0f)
                    close()
                    moveTo(13.4f, 15.4f)
                    verticalLineTo(28.0f)
                    horizontalLineTo(17.4f)
                    verticalLineTo(15.4f)
                    horizontalLineTo(13.4f)
                    close()
                    moveTo(28.0f, 13.4f)
                    horizontalLineTo(15.4f)
                    verticalLineTo(17.4f)
                    horizontalLineTo(28.0f)
                    verticalLineTo(13.4f)
                    close()
                    moveTo(26.0f, 12.6f)
                    verticalLineTo(15.4f)
                    horizontalLineTo(30.0f)
                    verticalLineTo(12.6f)
                    horizontalLineTo(26.0f)
                    close()
                    moveTo(15.4f, 14.6f)
                    horizontalLineTo(28.0f)
                    verticalLineTo(10.6f)
                    horizontalLineTo(15.4f)
                    verticalLineTo(14.6f)
                    close()
                    moveTo(13.4f, 0.0f)
                    verticalLineTo(12.6f)
                    horizontalLineTo(17.4f)
                    verticalLineTo(0.0f)
                    horizontalLineTo(13.4f)
                    close()
                }
            }
        }
        .build()
        return _iconPlus!!
    }

private var _iconPlus: ImageVector? = null
