package com.captures2024.soongan.core.designsystem.icon.myiconpack

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType.Companion.NonZero
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap.Companion.Butt
import androidx.compose.ui.graphics.StrokeJoin.Companion.Miter
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.ImageVector.Builder
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.captures2024.soongan.core.designsystem.icon.MyIconPack

public val MyIconPack.IconPlusBig: ImageVector
    get() {
        if (_iconPlusBig != null) {
            return _iconPlusBig!!
        }
        _iconPlusBig = Builder(name = "IconPlusBig", defaultWidth = 44.0.dp, defaultHeight = 44.0.dp,
                viewportWidth = 44.0f, viewportHeight = 44.0f).apply {
            group {
                path(fill = SolidColor(Color(0xFF252525)), stroke = null, strokeLineWidth = 0.0f,
                        strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                        pathFillType = NonZero) {
                    moveTo(20.0003f, 0.0f)
                    verticalLineTo(-2.0f)
                    horizontalLineTo(18.0003f)
                    verticalLineTo(0.0f)
                    horizontalLineTo(20.0003f)
                    close()
                    moveTo(24.0003f, 0.0f)
                    horizontalLineTo(26.0003f)
                    verticalLineTo(-2.0f)
                    horizontalLineTo(24.0003f)
                    verticalLineTo(0.0f)
                    close()
                    moveTo(20.0003f, 18.0f)
                    verticalLineTo(20.0f)
                    horizontalLineTo(22.0003f)
                    verticalLineTo(18.0f)
                    horizontalLineTo(20.0003f)
                    close()
                    moveTo(2.0f, 18.0f)
                    verticalLineTo(16.0f)
                    horizontalLineTo(0.0f)
                    verticalLineTo(18.0f)
                    horizontalLineTo(2.0f)
                    close()
                    moveTo(2.0f, 22.0f)
                    horizontalLineTo(0.0f)
                    verticalLineTo(24.0f)
                    horizontalLineTo(2.0f)
                    verticalLineTo(22.0f)
                    close()
                    moveTo(20.0003f, 22.0f)
                    horizontalLineTo(22.0003f)
                    verticalLineTo(20.0f)
                    horizontalLineTo(20.0003f)
                    verticalLineTo(22.0f)
                    close()
                    moveTo(20.0003f, 40.0f)
                    horizontalLineTo(18.0003f)
                    verticalLineTo(42.0f)
                    horizontalLineTo(20.0003f)
                    verticalLineTo(40.0f)
                    close()
                    moveTo(24.0003f, 40.0f)
                    verticalLineTo(42.0f)
                    horizontalLineTo(26.0003f)
                    verticalLineTo(40.0f)
                    horizontalLineTo(24.0003f)
                    close()
                    moveTo(24.0003f, 22.0f)
                    verticalLineTo(20.0f)
                    horizontalLineTo(22.0003f)
                    verticalLineTo(22.0f)
                    horizontalLineTo(24.0003f)
                    close()
                    moveTo(42.0f, 22.0f)
                    verticalLineTo(24.0f)
                    horizontalLineTo(44.0f)
                    verticalLineTo(22.0f)
                    horizontalLineTo(42.0f)
                    close()
                    moveTo(42.0f, 18.0f)
                    horizontalLineTo(44.0f)
                    verticalLineTo(16.0f)
                    horizontalLineTo(42.0f)
                    verticalLineTo(18.0f)
                    close()
                    moveTo(24.0003f, 18.0f)
                    horizontalLineTo(22.0003f)
                    verticalLineTo(20.0f)
                    horizontalLineTo(24.0003f)
                    verticalLineTo(18.0f)
                    close()
                    moveTo(20.0003f, 2.0f)
                    horizontalLineTo(24.0003f)
                    verticalLineTo(-2.0f)
                    horizontalLineTo(20.0003f)
                    verticalLineTo(2.0f)
                    close()
                    moveTo(22.0003f, 18.0f)
                    verticalLineTo(0.0f)
                    horizontalLineTo(18.0003f)
                    verticalLineTo(18.0f)
                    horizontalLineTo(22.0003f)
                    close()
                    moveTo(2.0f, 20.0f)
                    horizontalLineTo(20.0003f)
                    verticalLineTo(16.0f)
                    horizontalLineTo(2.0f)
                    verticalLineTo(20.0f)
                    close()
                    moveTo(4.0f, 22.0f)
                    verticalLineTo(18.0f)
                    horizontalLineTo(0.0f)
                    verticalLineTo(22.0f)
                    horizontalLineTo(4.0f)
                    close()
                    moveTo(20.0003f, 20.0f)
                    horizontalLineTo(2.0f)
                    verticalLineTo(24.0f)
                    horizontalLineTo(20.0003f)
                    verticalLineTo(20.0f)
                    close()
                    moveTo(22.0003f, 40.0f)
                    verticalLineTo(22.0f)
                    horizontalLineTo(18.0003f)
                    verticalLineTo(40.0f)
                    horizontalLineTo(22.0003f)
                    close()
                    moveTo(24.0003f, 38.0f)
                    horizontalLineTo(20.0003f)
                    verticalLineTo(42.0f)
                    horizontalLineTo(24.0003f)
                    verticalLineTo(38.0f)
                    close()
                    moveTo(22.0003f, 22.0f)
                    verticalLineTo(40.0f)
                    horizontalLineTo(26.0003f)
                    verticalLineTo(22.0f)
                    horizontalLineTo(22.0003f)
                    close()
                    moveTo(42.0f, 20.0f)
                    horizontalLineTo(24.0003f)
                    verticalLineTo(24.0f)
                    horizontalLineTo(42.0f)
                    verticalLineTo(20.0f)
                    close()
                    moveTo(40.0f, 18.0f)
                    verticalLineTo(22.0f)
                    horizontalLineTo(44.0f)
                    verticalLineTo(18.0f)
                    horizontalLineTo(40.0f)
                    close()
                    moveTo(24.0003f, 20.0f)
                    horizontalLineTo(42.0f)
                    verticalLineTo(16.0f)
                    horizontalLineTo(24.0003f)
                    verticalLineTo(20.0f)
                    close()
                    moveTo(22.0003f, 0.0f)
                    verticalLineTo(18.0f)
                    horizontalLineTo(26.0003f)
                    verticalLineTo(0.0f)
                    horizontalLineTo(22.0003f)
                    close()
                }
            }
        }
        .build()
        return _iconPlusBig!!
    }

private var _iconPlusBig: ImageVector? = null
